### ISSUE TITLE
Question about Licence and Docker

### ISSUE THREAD

**Issue by 7homasSutter** [FICS/BigMAC#2]
Hi there!

First of all, this framework seems pretty awesome! I'm working on a project to automate the analysis of Android firmware and I would like to integrate parts of your framework into my tool. However, I have some questions:

- Under what Licence is your framework? I couldn't find any licence file in this repository
- Do you think your framework would run within a docker container? If so I would like to build one

Kind Regards

Tom

**Comment by grant-h** [comment]
Hi Tom. BigMAC is licensed as BSD-3. BigMAC has two main components: the extraction and the parsing/querying. The extraction part has a ton of dependencies that would need pulling in and compiling, while the parsing side has relatively little dependencies. The README is a good starting point for getting the commands needed to compile this in a Docker container.

**Comment by 7homasSutter** [comment]
Thanks a lot for taking the time to respond! I will see what I can do.
