### ISSUE TITLE
Documentation and samples

### ISSUE THREAD

**Issue by P3nguin-M** [FICS/BigMAC#7]
Using samples in Eval doesn't seem to work unless there's a part missing of actual method to extract firmware, its policies, etc. 

`./process.py --vendor aosp eval/policy/aosp/sailfish-pq2a.190205.003-factory-164a7269/ --load --prolog
BigMAC Android Policy Processor
 by Grant Hernandez (https://hernan.de/z)

ERROR: Policy directory does not exist or is not readable

`
Also have tried to extract policies with extract.py but throws errors on sefcontext_parser (which is imported and was confirmed being importable) Any help would be great, would love to check out this tool but have not been able to get it to work for 3 days after many code changes back/forth. Help!!!?
Telegram anything? LMK

**Comment by P3nguin-M** [comment]
Have found that you cannot call the policy being inside of eval. Strips off eval and the file directory reads as False. Copying the policy over to root folder fixes this. May want to fix that, just still unsure of a good fix than hardcoding the "/eval" folder into it.

**Comment by usususj** [comment]
Hi @P3nguin-M 

ERROR: Policy directory does not exist or is not readable

I'm getting same error. How did you solve the problem?
It would be very helpful if you could share the solution.
